In [1]:
import numpy as np

In [3]:
x=np.zeros((3,4))

In [4]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
x=np.ones((2,3,4) , dtype='int16')

In [6]:
x

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
x=np.arange(10,25,5)

In [8]:
x

array([10, 15, 20])

In [9]:
x=np.linspace(0,2,9)

In [10]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [11]:
x=np.full((2,2),7)

In [12]:
x

array([[7, 7],
       [7, 7]])

In [13]:
x=np.eye(2,2)

In [14]:
x

array([[1., 0.],
       [0., 1.]])

In [16]:
x=np.random.random((2,2))

In [17]:
x

array([[0.15945902, 0.13565904],
       [0.80110952, 0.61044983]])

In [18]:
x=np.array([[2,4,6],[8,5,6]])

In [19]:
x


array([[2, 4, 6],
       [8, 5, 6]])

In [20]:
i=np.transpose(x)


In [21]:
i

array([[2, 8],
       [4, 5],
       [6, 6]])

In [22]:
a=np.array([1,2,3])

In [23]:
b=np.array([2,3,4])

In [24]:
np.add(b,a)

array([3, 5, 7])

In [25]:
np.subtract(b,a)

array([1, 1, 1])